apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
      listen 80;
      listen [::]:80;
      server_name jlapp-nginx;

      proxy_http_version 1.1;
      proxy_set_header   Upgrade $http_upgrade;
      proxy_set_header   Connection "";
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $remote_addr;
      proxy_set_header   X-Forwarded-Proto $scheme;
      proxy_set_header   X-Forwarded-Host $host;
      proxy_set_header   X-Forwarded-Port $server_port;

      location /pagamento {
        proxy_pass http://pagamento;
      }
      
      location /pedido {
        proxy_pass http://pedido;
      }
      
      location /producao {
        proxy_pass http://producao;
      }
    }

    upstream pagamento {
      server jlapp-pagamento-service:8072;
    }
    
    upstream pedido {
      server jlapp-pedido-service:8070;
    }
    
    upstream producao {
      server jlapp-producao-service:8074;
    }